### ISSUE TITLE
Django 1.9.2 - javascript printed instead of executed

### ISSUE THREAD

**Issue by tgy** [kaleidos/django-mathjax#7]
Using the very last version of django (`1.9.2` at the time of writing) I get the javascript printed instead of executed.

(I am using the exact same project that was working with a prior version of django)

I don't know why. Can you investigate?

**Comment by mhantke** [comment]
I have the same problem.

**Comment by cknoll** [comment]
Same problem here. But it seems easy to fix, see https://docs.djangoproject.com/en/1.9/ref/utils/#django.utils.safestring.mark_safe,

I will file a PR.
